name: Run API Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      parallel_mode:
        description: 'Enable parallel mode (true/false)'
        required: false
        default: 'false'
      cucumber_tags:
        description: 'Cucumber tags for filtering scenarios'
        required: false
        default: '@api and not @Ignore'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # 3. Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # 4. Run Maven tests
      - name: Run Tests
        run: mvn clean test -Dparallel.mode=${{ github.event.inputs.parallel_mode }} -Dcucumber.filter.tags="${{github.event.inputs.cucumber_tags}}"

      # 5. Compress logs folder and upload as Artifact
      - name: Compress Logs
        run: zip -r logs.zip logs/

      - name: Upload Logs Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Logs
          path: logs.zip
